stages:
  - force_push_to_github
  - build
  - package

variables:
  GITHUB_REPO_URL: "https://github.com/nesi/agdr-validator.git"
  GIT_TAG: "v1.3"
  PYTHON_VERSION: "3.9"  
  APP_NAME: "agdrvalidator1_6"       

force_push_to_github:
  stage: force_push_to_github
  script:
    - chmod +x copy_and_tag_to_github.sh
    - ./copy_and_tag_to_github.sh $GITHUB_REPO_URL $GIT_TAG
  when: manual

build:windows:
  stage: build
  image: python:${PYTHON_VERSION}-windowsservercore
  tags:
    - windows
  script:
    - cd src/agdrvalidator
    - pip install pyinstaller
    - pyinstaller --onefile --add-data=data/dictionaries/gen3.nesi_2025_09_01.json:agdrvalidator/data/dictionaries  --name ${APP_NAME}-win __main__.py
  artifacts:
    paths:
      - dist/
    expire_in: 1 day
  when: manual
  allow_failure: true

# Build for macOS (Manual)
build:macos:
  stage: build
  tags:
    - saas-macos-large-m2pro
  script:
    - cd src/agdrvalidator
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install pyinstaller
    - pyinstaller --onefile --add-data=data/dictionaries/gen3.nesi_2025_09_01.json:agdrvalidator/data/dictionaries  --name ${APP_NAME}-mac __main__.py
    - xattr -dr com.apple.quarantine dist/{APP_NAME}-mac
  artifacts:
    paths:
      - dist/
    expire_in: 1 day
  when: manual
  allow_failure: true

# Build for Linux (Manual)
build:linux:
  stage: build
  image: python:${PYTHON_VERSION}-slim
  script:
    - cd src/agdrvalidator
    - apt-get update && apt-get install -y binutils
    - pip install pyinstaller
    - pyinstaller --onefile --add-data=data/dictionaries/gen3.nesi_2025_09_01.json:agdrvalidator/data/dictionaries  --name ${APP_NAME}-linux __main__.py
  artifacts:
    paths:
      - dist/
    expire_in: 1 day
  when: manual
  allow_failure: true

# Package Windows build
package:windows:
  stage: package
  image: alpine:latest
  needs:
    - job: build:windows
      optional: true
  dependencies:
    - build:windows
  script:
    - apk add --no-cache tar
    - cd dist
    - tar -czf ${APP_NAME}-windows.tar.gz ${APP_NAME}-win.exe
    - cd ..
  artifacts:
    paths:
      - dist/${APP_NAME}-windows.tar.gz
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"
      when: on_success

# Package macOS build
package:macos:
  stage: package
  image: alpine:latest
  needs:
    - job: build:macos
      optional: true
  dependencies:
    - build:macos
  script:
    - apk add --no-cache tar
    - cd dist
    - tar -czf ${APP_NAME}-macos.tar.gz ${APP_NAME}-macos
    - cd ..
  artifacts:
    paths:
      - dist/${APP_NAME}-macos.tar.gz
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"
      when: on_success

# Package Linux build
package:linux:
  stage: package
  image: alpine:latest
  needs:
    - job: build:linux
      optional: true
  dependencies:
    - build:linux
  script:
    - apk add --no-cache tar
    - cd dist
    - tar -czf ${APP_NAME}-linux.tar.gz ${APP_NAME}-linux
    - cd ..
  artifacts:
    paths:
      - dist/${APP_NAME}-linux.tar.gz
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"
      when: on_success